# Generated by Django 3.1 on 2020-09-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailverification',
            table='modules_email_verification',
        ),
        migrations.AlterModelTable(
            name='mobileverification',
            table='modules_mobile_verification',
        ),
        migrations.AlterModelTable(
            name='user',
            table='modules_user',
        ),
    ]
