# Generated by Django 3.1 on 2020-09-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200908_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverification',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='mobileverification',
            old_name='user_id',
            new_name='user',
        ),
    ]
