# Generated by Django 3.1 on 2020-09-10 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200908_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 14, 29, 41, 935519)),
        ),
        migrations.AddField(
            model_name='mobileverification',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 14, 29, 41, 936451)),
        ),
    ]
