# Generated by Django 3.1 on 2020-09-10 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200910_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 18, 39, 17, 361164)),
        ),
        migrations.AlterField(
            model_name='mobileverification',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 17, 44, 16, 361811)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='email verified at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_verified_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='mobile verified at'),
        ),
    ]
