# Generated by Django 3.0.10 on 2020-09-10 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20200910_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 23, 49, 20, 997702)),
        ),
        migrations.AlterField(
            model_name='mobileverification',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 22, 54, 19, 998514)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
