# Generated by Django 3.0.10 on 2020-09-10 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20200910_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 23, 49, 53, 624907)),
        ),
        migrations.AlterField(
            model_name='mobileverification',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 10, 22, 54, 52, 625587)),
        ),
    ]
